## Register ##
POST http://localhost:5001/api/auth/register
Content-Type: application/json

{
    "username": "testuser01",
    "email": "testuser01@gmail.com",
    "password": "password123"
}

## Login ##
POST http://localhost:5001/api/auth/login
Content-Type: application/json

{
    "email": "testuser01@gmail.com",
    "password": "password123"
}

## Create Room ##
POST http://localhost:5001/api/rooms
Content-Type: application/json
Authorization: Bearer ----

{
    "name": "Chatting Room",
    "description": "This is a chatting room." 
}

## Get Rooms ##
GET http://localhost:5001/api/rooms
Content-Type: application/json
Authorization: Bearer ----

## Sent message in room ##
POST http://localhost:5001/api/messages
Content-Type: application/json
Authorization: Bearer ----

{
    "roomId": "",
    "content": "Hello Test Message"
}

## Fetch Messages ##
GET  http://localhost:5001/api/messages/----
Content-Type: application/json
Authorization: Bearer ----